# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformInit
    displayName: Terraform init
    jobs:
    # Install latest terraform on agent and run init
    - job: TerraformInstallSetUp 
      displayName: Install terraform latest and terrafrom init
      steps:
        - task: TerraformInstaller@1
          displayName: "Latest Version of terraform installation"
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'BeStrong'
            backendAzureRmResourceGroupName: 'tf-tfstate-ResourceGroup'
            backendAzureRmStorageAccountName: 'tfstatestac3e7d7b3d'
            backendAzureRmContainerName: 'tf-tfstate-for-production'
            backendAzureRmKey: 'prod.tfstate'
        - task: TerraformTaskV4@4
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

  # - stage: TerraformValidate
  #   dependsOn: TerraformInit
  #   displayName: Terraform validate
  #   jobs:
  #   - job:
  #     displayName: Validate Terraform configuration
  #     steps:
  #       - task: TerraformTaskV4@4
  #         displayName: terraform validate
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'validate'







# steps:

# - task: TerraformInstaller@1
#   displayName: "Latest Version of terraform installation"
#   inputs:
#     terraformVersion: 'latest'

# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     backendServiceArm: 'BeStrong'
#     backendAzureRmResourceGroupName: 'tf-tfstate-ResourceGroup'
#     backendAzureRmStorageAccountName: 'tfstatestac3e7d7b3d'
#     backendAzureRmContainerName: 'tf-tfstate-for-production'
#     backendAzureRmKey: 'prod.tfstate'
