trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
      - README.md
      - pipelines

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformInit
    displayName: Terraform init and validate
    jobs:
    # Install latest terraform on agent and run init
    - job: TerraformInstallSetUp 
      displayName: Install terraform latest and terrafrom init
      steps:
        - task: TerraformInstaller@1
          displayName: "Latest Version of terraform installation"
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'BeStrong'
            backendAzureRmResourceGroupName: 'tf-tfstate-ResourceGroup'
            backendAzureRmStorageAccountName: 'tfstatestac3e7d7b3d'
            backendAzureRmContainerName: 'tf-tfstate-for-production'
            backendAzureRmKey: 'prod.tfstate'
    # Validate terraform configuration
    - job: TerraformValidate
      displayName: Validate terraform configuration
      steps:
        - task: TerraformTaskV4@4
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
