trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - pipelines

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - pipelines

pool:
  vmImage: ubuntu-latest



jobs:
  - job: PullRequest
    displayName: Test validation and terraform plan
    condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'))
    steps:
      - template: pull-request-pipeline.yml

  - job: TestPullRequest
    displayName: Test on pull request
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: echo "This is a pull request event."
        displayName: 'Echo Pull Request'








# stages:
#     - stage: OnCommit
#       displayName: Infrastructure build
      




















# jobs:
#   - job: TestCommit
#     displayName: Test on commit
#     condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'))
#     steps:
#       - script: echo "This is a commit event."
#         displayName: 'Echo Commit'

#   - job: TestPullRequest
#     displayName: Test on pull request
#     condition: eq(variables['Build.Reason'], 'PullRequest')
#     steps:
#       - script: echo "This is a pull request event."
#         displayName: 'Echo Pull Request'