trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - pipelines

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - pipelines




stages:
- stage: Commit
  displayName: Infrastructure rebuild 
  condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'))
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: TerraformApply
    displayName: Code validation and infrastructure deploy (terraform validate/aplly)  
    steps:
      - template: templates/commit-template.yml
- stage: PullRequest
  displayName: Test build
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: TerraformPlan
      displayName: Code validation and dry run (terraform validate/plan) 
      steps:
        - template: templates/pull-request-template.yml